### ISSUE TITLE
20231031 중간 이전 전체 검토 결과

### ISSUE THREAD

**Issue by MisooKim2** [nayejun626/C202309#4]
### 없는 파일
- challenge/week5/functionMulti.c
- practice/week4/pyramid.c
- practice/week7/7_travel.c
	위 파일 이름이나 위치를 다시 확인하세요. 해당 소스 파일 채점이 수행되지 않습니다.

### 워닝 있음. 아래 파일/워닝메세지/솔루션을 확인하세요
- WARNING in challenge/week3/choiceIf
    - Warning: 'scanf' is deprecated: This function or variable may be unsafe. Consider using scanf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [line 9]
        - scanf_s 함수를 사용하세요.

- WARNING in challenge/week3/zeroTwoIf
    - Warning: 'scanf' is deprecated: This function or variable may be unsafe. Consider using scanf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [line 7]
          - scanf_s 함수를 사용하세요.

- WARNING in challenge/week4/pyramidReverse
    - Warning: 'scanf' is deprecated: This function or variable may be unsafe. Consider using scanf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [line 7]
        - scanf_s 함수를 사용하세요.
        
- WARNING in challenge/week6/studentGrade
    - Warning: 'scanf' is deprecated: This function or variable may be unsafe. Consider using scanf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [line 62]
    - Warning: 'scanf' is deprecated: This function or variable may be unsafe. Consider using scanf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [line 69]
        - scanf_s 함수를 사용하세요.

- WARNING in practice/week5/functionHap
    - Warning: return type of 'main' is not 'int' [line 4]
         - main 함수에 반환형과 반환값을 추가해주세요.

- WARNING in practice/week6/studentGrade
    - Warning: 'scanf' is deprecated: This function or variable may be unsafe. Consider using scanf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [line 49]
    - Warning: 'scanf' is deprecated: This function or variable may be unsafe. Consider using scanf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [line 56]
         - scanf_s 함수를 사용하세요.

- WARNING in project/week8/todo_manager
    - Warning: 'scanf' is deprecated: This function or variable may be unsafe. Consider using scanf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [line 26]
    - Warning: 'scanf' is deprecated: This function or variable may be unsafe. Consider using scanf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [line 34]
    - Warning: 'scanf' is deprecated: This function or variable may be unsafe. Consider using scanf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [line 45]
    - Warning: 'strcpy' is deprecated: This function or variable may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [line 57]
    - Warning: 'strcpy' is deprecated: This function or variable may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [line 60]
    - Warning: 'scanf' is deprecated: This function or variable may be unsafe. Consider using scanf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [line 78]
    - Warning: 'scanf' is deprecated: This function or variable may be unsafe. Consider using scanf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [line 87]
- WARNING in project/week8/todo_manager_func
    - Warning: 'scanf' is deprecated: This function or variable may be unsafe. Consider using scanf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [line 16]
    - Warning: 'strncpy' is deprecated: This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [line 17]
    - Warning: 'scanf' is deprecated: This function or variable may be unsafe. Consider using scanf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [line 32]
    - Warning: 'strncpy' is deprecated: This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [line 44]
    - Warning: 'scanf' is deprecated: This function or variable may be unsafe. Consider using scanf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [line 77]
    - Warning: 'scanf' is deprecated: This function or variable may be unsafe. Consider using scanf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [line 96]
    - Warning: 'scanf' is deprecated: This function or variable may be unsafe. Consider using scanf_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [line 106]
    - Warning: 'strncpy' is deprecated: This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [line 107]
        - scanf_s, strcpy_s, strncpy_s 함수를 사용하세요.

**Comment by MisooKim2** [comment]
나예준학생 안녕하세요.
맥북과 vs code를 사용하고 있기 때문에, scanf와 strcpy를 사용하고 있다는 것을 잘 알고 있습니다.
다만 scanf나 strcpy와 같이 "_s" 가 안붙은 것을 사용하시는 것은 코드의 보안 관점에서 지양해야 하는 점을 꼭 잊지 마셨으면 좋겠습니다.
그리고 개인 pc 내 환경을 visual stdio로 변경하시는 것을 추천드립니다.

_s 붙인 코드로 변경 후 컴파일이 어려우신 경우, 해당 에러나 워닝은 해결 없이 나머지 문제라도 해결해주시길 바랍니다.

**Comment by nayejun626** [comment]
scanf_s ㅁ문제를 제외하곤 모두 커밋했습니다.
